name: Build Samples

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0

      - name: Build samples
        working-directory: samples/core
        run: dotnet build
