name: Build Samples

on:
  push:
    branches: [master]
    paths:
      - "samples/core/**"
      - ".github/workflows/build-samples.yml"
  pull_request:
    branches: [master]
    paths:
      - "samples/core/**"
      - ".github/workflows/build-samples.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core 3.1 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup .NET 5.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rc.2.20479.15

      - name: Build samples
        working-directory: samples/core
        run: dotnet build
